<a href="https://colab.research.google.com/github/gusdelact/mymachinelearning/blob/main/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
#matriz de 2 renglone por 4 columnas 2 x 4
mt0 = [
       [3,4,5,6] ,
       [7,8,8,9]
]

print(mt0[0])
print(mt0[1])

[3, 4, 5, 6]
[7, 8, 8, 9]


In [22]:
#matriz de 4 renglones por 2 columnas 4 x 2
mt1 = [
       [-3,2] ,
       [5,0] ,
       [4,0],
       [3,1]
]
print(mt1[0]) 
print(mt1[1]) 
print(mt1[2]) 

[-3, 2]
[5, 0]
[4, 0]


In [23]:
# matriz cuadrada de 3 x 3
mat2 = [
        [1 ,2 ,3],
        [-1 ,-2 , -3],
        [7, -8, -21]

]
print(mat2[0])
print(mat2[1])
print(mat2[2])
print(mat2[1][1])

[1, 2, 3]
[-1, -2, -3]
[7, -8, -21]
-2


In [24]:
#matriz cero de 2 x 2 
m_cero_2x2 = [
         [0,0] ,
         [0,0]         
]

In [25]:
#matriz cero de 3 x 3
m_cero_3x3 = [
         [0,0,0] ,
         [0,0,0] ,
         [0,0,0]         
]

In [26]:
#matriz unitaria de 2 x 2
m_unitaria_2x2 = [
         [1,0] ,
         [0,1]         
]

In [27]:
#matriz unitaria de 3 x 3
m_unitaria_3x3 = [
         [1,0,0] ,
         [0,1,0] ,
         [0,0,1]         
]

In [28]:
#matriz diagonal 3 x3
m_diagonal_3x3 = [
         [-7,0,0] ,
         [0,5,0] ,
         [0,0,10]               
]

In [29]:
#matrices triangulares
m_triangular_superior = [
      [4,5,6] ,
      [0,1,3], 
      [0,0,-2]                  
]
m_trianguar_inferior = [
      [4,0,0] ,
      [1,1,0], 
      [3,-3,-2]                  
]

In [30]:
#matriz transpuesta
mat3 = [ 
        [1,2],
        [3,4]
]
#los renglones se vuelven columnas y las columnas se vuelven renglones
mat3T = [
      [1,3],
      [2,4]
]

mat4 = [
    [4,5,6,7],
    [3,2,1,0]
]
mat4T= [
    [4,3],
    [5,2],
    [6,1],
    [7,0]    
]

In [31]:
#matriz simetrica 
mat5 = [
        [1,4,7],
        [4,2,5],
        [7,5,6]
]
mat5T= [
        [1,4,7],
        [4,2,5],
        [7,5,6]
]

mat5 == mat5T

True

In [34]:
mat6 = [ [1,3],
          [-1,5]  
      ]
det_mat6= mat6[0][0]*mat6[1][1] - mat6[0][1]* mat6[1][0]
print(det_mat6)

8


In [35]:
mat7 = [ [1,3],
          [3,9]  
      ]
det_mat7= mat7[0][0]*mat7[1][1] - mat7[0][1]* mat7[1][0]
print(det_mat7)

0


In [47]:
mat6 + mat7

[[1, 3], [-1, 5], [1, 3], [3, 9]]

In [ ]:
#mat6 - mat7

In [ ]:
#mat6 * mat7

In [42]:
import numpy as np

In [43]:
np_mat6=np.array(mat6)

In [44]:
np_mat7=np.array(mat7)

In [45]:
np_mat6 + np_mat7

array([[ 2,  6],
       [ 2, 14]])

In [46]:
np_mat6 - np_mat7

array([[ 0,  0],
       [-4, -4]])

In [50]:
#esto no es una producto cruz
np_mat6 * np_mat7

array([[ 1,  9],
       [-3, 45]])

In [52]:
#determinante de la matriz usando el modulo linalg
np.linalg.det(np_mat6)

7.999999999999998

In [54]:
np.linalg.det(np_mat7)

0.0

In [60]:
np.matmul(np_mat6,np_mat7)

array([[10, 30],
       [14, 42]])

In [57]:
#multiplicacion de matrices
np.dot(np_mat6,np_mat7)

array([[10, 30],
       [14, 42]])

In [66]:
np_mat6.dot(np_mat7)

array([[10, 30],
       [14, 42]])

In [62]:
np.linalg.inv(np_mat6)

array([[ 0.625, -0.375],
       [ 0.125,  0.125]])

In [64]:

np.linalg.inv(np_mat6).dot(np_mat6)

array([[1., 0.],
       [0., 1.]])

In [65]:
np.dot( np_mat6, np.linalg.inv(np_mat6) )

array([[1., 0.],
       [0., 1.]])

In [68]:
np_mat6@np_mat7

array([[10, 30],
       [14, 42]])

In [83]:
np_arr1=np.array([1,2,3])
np_arr2=np.array([4,5,6])
np_arr1.dot(np_arr2)


32

In [85]:
np.inner(np_arr1,np_arr2)

32

In [91]:
np_mat5  = np.matrix(mat5)
np_mat5T = np_mat5.transpose()

In [92]:
np_mat5

matrix([[1, 4, 7],
        [4, 2, 5],
        [7, 5, 6]])

In [93]:
np_mat5T

matrix([[1, 4, 7],
        [4, 2, 5],
        [7, 5, 6]])

In [98]:
np.matrix([
    [1,2,3],
    [4,5,6]
]
).dot(
np.matrix(
    [
     [6,7,8,9],
     [0,1,2,3],
     [4,5,6,7]
    ]
)
)

matrix([[18, 24, 30, 36],
        [48, 63, 78, 93]])

In [99]:
np.array([
    [1,2,3],
    [4,5,6]
]
).dot(
np.array(
    [
     [6,7,8,9],
     [0,1,2,3],
     [4,5,6,7]
    ]
)
)

array([[18, 24, 30, 36],
       [48, 63, 78, 93]])

In [103]:
np.inner(
    np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
),
np.array(
    [
     [6,7,8],
     [0,1,2],
     [4,5,6]
    ]
)
)

array([[ 44,   8,  32],
       [107,  17,  77],
       [170,  26, 122]])

In [116]:
#solucion de ecuaciones simultaneas
# A*x=b

A= np.matrix(
  [
    [2,3,-4],
    [1,-1,3],
    [2,5,-1]
  ]
)
b= np.matrix( [
      [-4],
      [8] ,
      [9]        
  ]
)

A_inv=np.linalg.inv(A)
x= A_inv.dot(b)

In [117]:
x

matrix([[1.],
        [2.],
        [3.]])

In [118]:
np.linalg.solve(A,b)

matrix([[1.],
        [2.],
        [3.]])

In [125]:
A=np.matrix(
  [
    [1,6,-2],
    [1,-3,7],
    [5,1,1],
  ]
)
b=np.matrix([7,16,10])
x=np.linalg.solve(A,b.transpose())
x

matrix([[1.],
        [2.],
        [3.]])

In [123]:
A.dot(x)

matrix([[-5.55111512e-17],
        [ 1.00000000e+00],
        [ 2.00000000e+00],
        [ 2.77555756e-17]])